# Generated by Django 5.0.1 on 2024-01-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoriya_post_remove_portfolio_text_portfolio_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=250)),
                ('data', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
